name: PHP Composer

on:
  push:
    branches: [ master, dev, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug    
          tools: php-cs-fixer, phpunit

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run:
          vendor/phpunit/phpunit/phpunit

      - name: Run phpcs, phpmd and report with reviewdog
        uses: lifulltechvn/laravel-app-reviewdog-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Reporter of reviewdog command [github-pr-check,github-pr-review].
          reporter: github-pr-check
          # Report level for reviewdog [info,warning,error]
          level: error
          # Arguments to pass to phpcs
          phpcs_args: .
          # Arguments to pass to phpmd
          phpmd_args: .
          # The subdirectory to execute the action in.
          directory: .

      - name: PHP STatic ANalyser (phpstan)
        uses: chindit/actions-phpstan@1.0.1
        with:
          # Arguments to add to PHPStan CLI
          arguments: --level 3 src

      - name: PHPUnit (php-actions)
        uses: php-actions/phpunit@v2
        with:
          # What version of PHPUnit to use
          version: 9.4
          # What version of PHP to use
          php_version: 7.4
