name: Bump version based on PR label - major, feature, bug
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PssbleTrngle/VersionManagment@v2
        id: version
        with:
            token: ${{secrets.GITHUB_TOKEN}}
            fallback: v0.1.0
            prefix: v
